# Generated by Django 2.2.3 on 2019-07-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='index_descripton',
            field=models.CharField(default='Главная', max_length=30, verbose_name='Главная - Descripton страницы'),
        ),
        migrations.AddField(
            model_name='page',
            name='index_keywords',
            field=models.CharField(default='Главная', max_length=30, verbose_name='Главная - Keywords страницы'),
        ),
        migrations.AddField(
            model_name='page',
            name='index_title',
            field=models.CharField(default='Главная', max_length=30, verbose_name='Главная - Title страницы'),
        ),
    ]
