# Generated by Django 2.2.3 on 2019-07-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190712_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='email',
            field=models.EmailField(blank=True, default='Нет данных', max_length=255, verbose_name='Поле - Email'),
        ),
        migrations.AlterField(
            model_name='forms',
            name='name',
            field=models.CharField(default='Нет данных', max_length=255, verbose_name='Поле - Ваше имя'),
        ),
        migrations.AlterField(
            model_name='forms',
            name='phone',
            field=models.CharField(default='Нет данных', max_length=255, verbose_name='Поле - Телефон'),
        ),
    ]
