# Generated by Django 2.2.3 on 2019-07-14 19:03

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190714_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='about_descripton',
        ),
        migrations.RemoveField(
            model_name='page',
            name='category_item_descripton',
        ),
        migrations.RemoveField(
            model_name='page',
            name='category_item_keywords',
        ),
        migrations.RemoveField(
            model_name='page',
            name='category_item_title',
        ),
        migrations.RemoveField(
            model_name='page',
            name='category_items_descripton',
        ),
        migrations.RemoveField(
            model_name='page',
            name='category_items_keywords',
        ),
        migrations.RemoveField(
            model_name='page',
            name='category_items_title',
        ),
        migrations.RemoveField(
            model_name='page',
            name='category_main_descripton',
        ),
        migrations.RemoveField(
            model_name='page',
            name='contact_descripton',
        ),
        migrations.RemoveField(
            model_name='page',
            name='index_descripton',
        ),
        migrations.RemoveField(
            model_name='page',
            name='services_item_descripton',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='Категория', max_length=30, verbose_name='Description '),
        ),
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=models.CharField(default='Категория', max_length=30, verbose_name='Keywords '),
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default='Категория', max_length=30, verbose_name='Title '),
        ),
        migrations.AddField(
            model_name='item',
            name='item_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Описание товара'),
        ),
        migrations.AddField(
            model_name='item',
            name='keywords',
            field=models.CharField(default='Портфолио', max_length=30, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(default='Портфолио', max_length=30, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='page',
            name='about_description',
            field=models.CharField(default='О НАС', max_length=30, verbose_name='О нас - Description страницы'),
        ),
        migrations.AddField(
            model_name='page',
            name='category_main_description',
            field=models.CharField(default='Портфолио', max_length=30, verbose_name='Портфолио  - Description страницы'),
        ),
        migrations.AddField(
            model_name='page',
            name='contact_description',
            field=models.CharField(default='КОНТАКТЫ', max_length=30, verbose_name='Контакты - Description страницы'),
        ),
        migrations.AddField(
            model_name='page',
            name='index_description',
            field=models.CharField(default='Главная', max_length=30, verbose_name='Главная - Description страницы'),
        ),
        migrations.AddField(
            model_name='page',
            name='services_item_description',
            field=models.CharField(default='Услуги', max_length=30, verbose_name='Услуги - Description страницы'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='НАЗВАНИЕ КАТЕГОРИИ', max_length=30, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(default='Портфолио', max_length=30, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='page',
            name='category_main_keywords',
            field=models.CharField(default='Портфолио', max_length=30, verbose_name='Портфолио  - Keywords страницы'),
        ),
        migrations.AlterField(
            model_name='page',
            name='category_main_title',
            field=models.CharField(default='Портфолио', max_length=30, verbose_name='Портфолио  - Title страницы'),
        ),
        migrations.AlterField(
            model_name='page',
            name='services_item_keywords',
            field=models.CharField(default='Услуги', max_length=30, verbose_name='Услуги - Keywords страницы'),
        ),
        migrations.AlterField(
            model_name='page',
            name='services_item_title',
            field=models.CharField(default='Услуги', max_length=30, verbose_name='Услуги - Title страницы'),
        ),
    ]
