# Generated by Django 2.2.3 on 2019-07-30 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_page_contact_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='temp_images', verbose_name='Изображение')),
            ],
        ),
        migrations.AlterField(
            model_name='aboutslider',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Показывать на странице?'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='category_images', verbose_name='Картинка категории'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Item', verbose_name='Изображение для товара'),
        ),
    ]
